### ISSUE TITLE
Fixati URI za konekciju baze u .env 

### ISSUE THREAD

**Issue by JovanJevtic** [JevticBusiness/Hacktoberfest-Aleksa-Jovan#8]
U .env file ispraviti URI (mongodb+srv://Hacktoberfest2020:<password>@hacktoberfest2020.u8z1q.mongodb.net/) <password> zamjeniti sifrom i onda gitignorati .env fajlove

**Comment by Aleksit0** [comment]
Radim na tome👉🏻
